[project]
name = "multimedia"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dash>=3.0.4",
    "einops>=0.8.1",
    "jaxtyping>=0.2.19",
    "matplotlib>=3.7.5",
    "pandas>=2.0.3",
    "plotly>=6.1.2",
    "torch>=2.5.1",
    "tqdm>=4.67.1",
    "transformer-lens>=2.15.4",
]
