[project]
name = "multimedia"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "dash>=3.0.4",
    "matplotlib>=3.7.5",
    "pandas>=2.0.3",
    "plotly>=6.1.2",
    "tqdm>=4.67.1",
]
